name: Local DeepSeek Config
version: 1.0.0
schema: v1
models:
  - name: DeepSeek Coder V2 Lite
    provider: openai
    apiBase: http://mac:1234/v1
    model: deepseek-coder-v2-lite-instruct
    roles:
      - chat
      - edit
      - apply
      - summarize